// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/crownsegmentr.h"
#include <Rcpp.h>

using namespace Rcpp;

// calculate_modes
Rcpp::DataFrame calculate_modes(const Rcpp::DataFrame& coordinate_table, const double& crown_diameter_to_tree_height, const double& crown_height_to_tree_height, const spatial::distance_t& centroid_convergence_distance, const int max_num_centroids_per_mode, const bool show_progress_bar);
RcppExport SEXP _crownsegmentr_calculate_modes(SEXP coordinate_tableSEXP, SEXP crown_diameter_to_tree_heightSEXP, SEXP crown_height_to_tree_heightSEXP, SEXP centroid_convergence_distanceSEXP, SEXP max_num_centroids_per_modeSEXP, SEXP show_progress_barSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type coordinate_table(coordinate_tableSEXP);
    Rcpp::traits::input_parameter< const double& >::type crown_diameter_to_tree_height(crown_diameter_to_tree_heightSEXP);
    Rcpp::traits::input_parameter< const double& >::type crown_height_to_tree_height(crown_height_to_tree_heightSEXP);
    Rcpp::traits::input_parameter< const spatial::distance_t& >::type centroid_convergence_distance(centroid_convergence_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_num_centroids_per_mode(max_num_centroids_per_modeSEXP);
    Rcpp::traits::input_parameter< const bool >::type show_progress_bar(show_progress_barSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_modes(coordinate_table, crown_diameter_to_tree_height, crown_height_to_tree_height, centroid_convergence_distance, max_num_centroids_per_mode, show_progress_bar));
    return rcpp_result_gen;
END_RCPP
}
// calculate_modes_plus_centroids
Rcpp::List calculate_modes_plus_centroids(const Rcpp::DataFrame& coordinate_table, const double& crown_diameter_to_tree_height, const double& crown_height_to_tree_height, const spatial::distance_t& centroid_convergence_distance, const int max_num_centroids_per_mode, const bool show_progress_bar);
RcppExport SEXP _crownsegmentr_calculate_modes_plus_centroids(SEXP coordinate_tableSEXP, SEXP crown_diameter_to_tree_heightSEXP, SEXP crown_height_to_tree_heightSEXP, SEXP centroid_convergence_distanceSEXP, SEXP max_num_centroids_per_modeSEXP, SEXP show_progress_barSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type coordinate_table(coordinate_tableSEXP);
    Rcpp::traits::input_parameter< const double& >::type crown_diameter_to_tree_height(crown_diameter_to_tree_heightSEXP);
    Rcpp::traits::input_parameter< const double& >::type crown_height_to_tree_height(crown_height_to_tree_heightSEXP);
    Rcpp::traits::input_parameter< const spatial::distance_t& >::type centroid_convergence_distance(centroid_convergence_distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_num_centroids_per_mode(max_num_centroids_per_modeSEXP);
    Rcpp::traits::input_parameter< const bool >::type show_progress_bar(show_progress_barSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_modes_plus_centroids(coordinate_table, crown_diameter_to_tree_height, crown_height_to_tree_height, centroid_convergence_distance, max_num_centroids_per_mode, show_progress_bar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_crownsegmentr_calculate_modes", (DL_FUNC) &_crownsegmentr_calculate_modes, 6},
    {"_crownsegmentr_calculate_modes_plus_centroids", (DL_FUNC) &_crownsegmentr_calculate_modes_plus_centroids, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_crownsegmentr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
